lib/stripe_ui/web/router.ex
defmodule StripeUi.Web.Router do
  use StripeUi.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StripeUi.Web do
    pipe_through :browser
    get "/", PageController, :index
    get "/charge", ChargeController, :index
    get "/customer", CustomerController, :index
    get "/token", TokenController, :index
  end

  scope "/api", StripeUi.Web do
    pipe_through :api
    post "/tokens", TokenController, :create
  end

end

lib/stripe_ui/web/controllers/charge_controller.ex
defmodule StripeUi.Web.ChargeController do
  use StripeUi.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/stripe_ui/web/controllers/customer_controller.ex
defmodule StripeUi.Web.CustomerController do
  use StripeUi.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/stripe_ui/web/controllers/page_controller.ex
defmodule StripeUi.Web.PageController do
  use StripeUi.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/stripe_ui/web/controllers/token_controller.ex
defmodule StripeUi.Web.TokenController do
  use StripeUi.Web, :controller
  alias StripeCallbacks.{Token,Repo}

  def index(conn, _params) do
    render conn, tokens: Repo.all(Token)
  end

  def create(conn, %{"token" => params, "mode" => mode}) do
    {:ok, token} = case mode do
      "create" -> Token.create(params)
      _ -> Token.process(params)
    end
    conn
    |> put_status(:created)
    |> render(token: token)
  end

  def analyze(conn, %{"token_identifier" => id}) do
    {:ok, token} = id |> Token.get_by_stripe_id |> Token.analyze
    conn
    |> render(token: token)
  end

end

lib/stripe_ui/web/views/charge_view.ex
defmodule StripeUi.Web.ChargeView do
  use StripeUi.Web, :view
end

lib/stripe_ui/web/views/customer_view.ex
defmodule StripeUi.Web.CustomerView do
  use StripeUi.Web, :view
end

lib/stripe_ui/web/views/error_view.ex
defmodule StripeUi.Web.ErrorView do
  use StripeUi.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/stripe_ui/web/views/layout_view.ex
defmodule StripeUi.Web.LayoutView do
  use StripeUi.Web, :view
end

lib/stripe_ui/web/views/page_view.ex
defmodule StripeUi.Web.PageView do
  use StripeUi.Web, :view
end

lib/stripe_ui/web/views/token_view.ex
defmodule StripeUi.Web.TokenView do
  use StripeUi.Web, :view

  def render("index.json", %{tokens: tokens}) do
    tokens
  end

  def render("create.json", %{token: token}) do
    token
  end

end

lib/stripe_ui/web/templates/charge/index.html.eex
<div class="stripe">
  <div class="container bordered">
    <div>
      <h1>Payment Gateway</h1>
      <h2>Invoice</h2>
      <form id="stripeForm" action="#" method="POST">
        <input id="stripePkey" type="hidden" value="<%= Application.get_env(:stripe_post, :public_key)%>">
        <input id="invoiceCurrency" type="hidden" value="cad">
        <input id="invoiceName" type="hidden" value="Payment Gateway">
        <div>
          <label>Description:</label>
          <input id="invoiceDescription" name="invoiceDescription">
        </div>
        <div>
          <label>Amount:</label>
          <input id="invoiceAmount" type="number" step="any" min="0" name="invoiceAmount">
        </div>
        <div class="buttons">
          <button id="stripeGo" data-mode="charge" class="btn ready">Pay Now</button>
        </div>
      </form>
    </div>
  </div>
</div>

lib/stripe_ui/web/templates/customer/index.html.eex
<div class="stripe">
  <div class="container bordered">
    <div>
      <h1>Customer</h1>
      <h2>Membership Sign Up</h2>
      <form id="stripeForm" action="/charge" method="POST">
        <input id="stripePkey" type="hidden" value="<%= Application.get_env(:stripe_post, :public_key)%>">
        <input id="invoiceCurrency" type="hidden" value="cad">
        <input id="invoiceName" type="hidden" value="Payment Gateway">
        <div>
          <label>Description:</label>
          <input id="invoiceDescription" name="invoiceDescription">
        </div>
        <div>
          <label>Recurring Amount:</label>
          <input id="invoiceAmount" type="number" step="any" min="0" name="invoiceAmount">
        </div>
        <div class="buttons">
          <button id="stripeGo" data-mode="customer" class="btn ready">Sign Up</button>
        </div>
      </form>
    </div>
  </div>
</div>

lib/stripe_ui/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Payment Gateway</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href="https://fonts.googleapis.com/css?family=Loved+by+the+King|Slabo+27px" rel="stylesheet">
    <script src="https://checkout.stripe.com/checkout.js"></script>
  </head>

  <body>
    <%= render @view_module, @view_template, assigns %>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/stripe_ui/web/templates/page/index.html.eex
<div class="home">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>Stripe API Integration</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="btn">
          <%= link "Make a Payment", to: charge_path(@conn, :index) %>
        </div>
      </div>
    </div>
<!--
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="btn">
          <%= link "Create Customer", to: customer_path(@conn, :index) %>
        </div>
      </div>
    </div>
-->
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="btn">
          <%= link "Create a Token", to: token_path(@conn, :index) %>
        </div>
      </div>
    </div>
  </div>
</div>

<!--
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>Stripe API Integration</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= link "Make a Payment", to: charge_path(@conn, :index) %>
      </div>
      <div class="col-6 btn-container">
        <%= link "Create a Customer", to: customer_path(@conn, :index) %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= link "Create a Token", to: charge_path(@conn, :index) %>
      </div>
      <div class="col-6 btn-container">
        <%= link "Analyze a Token", to: customer_path(@conn, :index) %>
      </div>
    </div>
  </div>
</div>
-->

lib/stripe_ui/web/templates/token/index.html.eex
<div class="stripe">
  <div class="container bordered">
    <div>
      <h1>Payment Gateway</h1>
      <h2>Invoice</h2>
      <form id="stripeForm" action="#" method="POST">
        <input id="stripePkey" type="hidden" value="<%= Application.get_env(:stripe_post, :public_key)%>">
        <input id="invoiceCurrency" type="hidden" value="cad">
        <input id="invoiceName" type="hidden" value="Payment Gateway">
        <div>
          <label>Description:</label>
          <input id="invoiceDescription" name="invoiceDescription">
        </div>
        <div>
          <label>Amount:</label>
          <input id="invoiceAmount" type="number" step="any" min="0" name="invoiceAmount">
        </div>
        <div>
          <label>Token:</label>
          <label id="stripeToken" name="stripeToken">TBD</label>
        </div>
        <div class="buttons">
          <button id="stripeGo" data-mode="token" class="btn ready">Create Token</button>
        </div>
      </form>
    </div>
  </div>
</div>